export const FETCH_USERS = "FETCH_USERS";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const FETCH_CLASSES = "FETCH_CLASS";
export const GET_CLASS_BY_ID = "GET_CLASS_BY_ID";
export const ADD_CLASS = "ADD_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";

export const ADD_CLASS_TO_QUECE = "ADD_CLASS_TO_QUECE";
export const GET_ALL_CLASS_FROM_QUECE = "GET_ALL_CLASS_FROM_QUECE";
export const DELETE_CLASS_FROM_QUECE = "DELETE_CLASS_FROM_QUECE";

export const ADD_TEACHER_TO_QUECE = "ADD_TEACHER_TO_QUECE";
export const GET_ALLTEACHER_FROM_QUECE = "GET_ALLTEACHER_FROM_QUECE";

export const GET_ALL_TEACHER = "GET_ALL_TEACHER";
